/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package healthprac;

import java.awt.Color;
import java.math.RoundingMode;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author DevUser
 */
public class jOrderMenu extends javax.swing.JFrame {

    /**
     * Creates new form jOrderday
     */
    public jOrderMenu() {
        try{
        initComponents();
        }catch(Exception e){
            
        }
    }
    //initialises order object for every day available
    Order mon = new Order("mon");
    Order tues = new Order("tues");
    Order wed = new Order("wed");
    Order thurs = new Order("thur");
    Order fri = new Order("fri");

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jBack1 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jMOFP = new javax.swing.JCheckBox();
        jMOHP = new javax.swing.JCheckBox();
        jMOSS = new javax.swing.JCheckBox();
        jMOJ = new javax.swing.JCheckBox();
        jLabel44 = new javax.swing.JLabel();
        MOrderButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTOFP = new javax.swing.JCheckBox();
        jTOHP = new javax.swing.JCheckBox();
        jTOM = new javax.swing.JCheckBox();
        jTOJ = new javax.swing.JCheckBox();
        jBack2 = new javax.swing.JButton();
        TOrderButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jBack3 = new javax.swing.JButton();
        WOrderButton = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jWOFP = new javax.swing.JCheckBox();
        jWOHP = new javax.swing.JCheckBox();
        jWOSR = new javax.swing.JCheckBox();
        jWOJ = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        jBack4 = new javax.swing.JButton();
        ThOrderButton = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jThOFP = new javax.swing.JCheckBox();
        jThOHP = new javax.swing.JCheckBox();
        jThOSS = new javax.swing.JCheckBox();
        jThOJ = new javax.swing.JCheckBox();
        jPanel5 = new javax.swing.JPanel();
        jBack5 = new javax.swing.JButton();
        FOrderButton = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jFOFP = new javax.swing.JCheckBox();
        jFOHP = new javax.swing.JCheckBox();
        jFOSR = new javax.swing.JCheckBox();
        jFOJ = new javax.swing.JCheckBox();
        jLabel41 = new javax.swing.JLabel();
        jBalLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(400, 300));

        jBack1.setText("Back");
        jBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBack1ActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 153, 51));
        jLabel1.setText("Full Panini");
        jLabel1.setOpaque(true);

        jLabel2.setBackground(new java.awt.Color(51, 255, 51));
        jLabel2.setText("Half Panini");
        jLabel2.setOpaque(true);

        jLabel3.setBackground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("Steak Slice");
        jLabel3.setOpaque(true);

        jLabel4.setBackground(new java.awt.Color(51, 255, 51));
        jLabel4.setText("Apple Juice");
        jLabel4.setOpaque(true);

        jLabel5.setText("£2.00");

        jLabel6.setText("£1.00");

        jLabel7.setText("£1.00");

        jLabel8.setText("£0.80");

        jMOFP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMOFPActionPerformed(evt);
            }
        });

        jMOHP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMOHPActionPerformed(evt);
            }
        });

        jMOSS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMOSSActionPerformed(evt);
            }
        });

        jMOJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMOJActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(89, 89, 89)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel44)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jMOHP))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addGap(44, 44, 44)
                            .addComponent(jMOFP))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7)
                                .addComponent(jLabel8))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jMOJ)
                                .addComponent(jMOSS)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5)
                    .addComponent(jMOFP))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6)
                    .addComponent(jMOHP))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7)
                    .addComponent(jMOSS))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jMOJ)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jLabel8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jLabel44)
                .addContainerGap())
        );

        MOrderButton.setText("Order");
        MOrderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MOrderButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jBack1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(MOrderButton))
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(152, 152, 152))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBack1)
                    .addComponent(MOrderButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane2.addTab("Monday", jPanel1);

        jLabel9.setBackground(new java.awt.Color(255, 153, 51));
        jLabel9.setText("Full Panini");
        jLabel9.setOpaque(true);

        jLabel10.setBackground(new java.awt.Color(51, 255, 51));
        jLabel10.setText("Half Panini");
        jLabel10.setOpaque(true);

        jLabel11.setBackground(new java.awt.Color(255, 0, 0));
        jLabel11.setText("Muffin");
        jLabel11.setOpaque(true);

        jLabel12.setBackground(new java.awt.Color(51, 255, 0));
        jLabel12.setText("Orange Juice");
        jLabel12.setOpaque(true);

        jLabel13.setText("£2.00");

        jLabel14.setText("£1.00");

        jLabel15.setText("£0.50");

        jLabel16.setText("£0.80");

        jTOFP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTOFPActionPerformed(evt);
            }
        });

        jTOHP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTOHPActionPerformed(evt);
            }
        });

        jTOM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTOMActionPerformed(evt);
            }
        });

        jTOJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTOJActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addGap(80, 80, 80)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTOJ))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTOM))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTOHP))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(44, 44, 44)
                        .addComponent(jTOFP)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel13)
                    .addComponent(jTOFP))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel14)
                    .addComponent(jTOHP))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel15)
                    .addComponent(jTOM))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel16)
                    .addComponent(jTOJ))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jBack2.setText("Back");
        jBack2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBack2ActionPerformed(evt);
            }
        });

        TOrderButton.setText("Order");
        TOrderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TOrderButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jBack2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 133, Short.MAX_VALUE)
                        .addComponent(TOrderButton))
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBack2)
                    .addComponent(TOrderButton))
                .addContainerGap())
        );

        jTabbedPane2.addTab("Tuesday", jPanel2);

        jBack3.setText("Back");
        jBack3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBack3ActionPerformed(evt);
            }
        });

        WOrderButton.setText("Order");
        WOrderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WOrderButtonActionPerformed(evt);
            }
        });

        jLabel17.setBackground(new java.awt.Color(255, 153, 0));
        jLabel17.setText("Full Panini");
        jLabel17.setOpaque(true);

        jLabel18.setBackground(new java.awt.Color(51, 255, 0));
        jLabel18.setText("Half Panini");
        jLabel18.setOpaque(true);

        jLabel19.setBackground(new java.awt.Color(255, 0, 0));
        jLabel19.setText("Sausage Roll");
        jLabel19.setOpaque(true);

        jLabel20.setBackground(new java.awt.Color(51, 255, 0));
        jLabel20.setText("Pineapple Juice");
        jLabel20.setOpaque(true);

        jLabel21.setText("£2.00");

        jLabel22.setText("£1.00");

        jLabel23.setText("£1.20");

        jLabel24.setText("£0.80");

        jWOFP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jWOFPActionPerformed(evt);
            }
        });

        jWOHP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jWOHPActionPerformed(evt);
            }
        });

        jWOSR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jWOSRActionPerformed(evt);
            }
        });

        jWOJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jWOJActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20))
                .addGap(71, 71, 71)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jWOJ))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jWOSR))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jWOHP))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addGap(44, 44, 44)
                        .addComponent(jWOFP)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel21)
                    .addComponent(jWOFP))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel22)
                    .addComponent(jWOHP))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jLabel23)
                    .addComponent(jWOSR))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jLabel24)
                    .addComponent(jWOJ))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jBack3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(WOrderButton))
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBack3)
                    .addComponent(WOrderButton))
                .addContainerGap())
        );

        jTabbedPane2.addTab("Wednesday", jPanel3);

        jBack4.setText("Back");
        jBack4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBack4ActionPerformed(evt);
            }
        });

        ThOrderButton.setText("Order");
        ThOrderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThOrderButtonActionPerformed(evt);
            }
        });

        jLabel25.setBackground(new java.awt.Color(255, 153, 0));
        jLabel25.setText("Full Panini");
        jLabel25.setOpaque(true);

        jLabel26.setBackground(new java.awt.Color(51, 255, 0));
        jLabel26.setText("Half Panini");
        jLabel26.setOpaque(true);

        jLabel27.setBackground(new java.awt.Color(255, 0, 0));
        jLabel27.setText("Steak Slice");
        jLabel27.setOpaque(true);

        jLabel28.setBackground(new java.awt.Color(51, 255, 0));
        jLabel28.setText("Orange Juice");
        jLabel28.setOpaque(true);

        jLabel29.setText("£2.00");

        jLabel30.setText("£1.00");

        jLabel31.setText("£1.00");

        jLabel32.setText("£0.80");

        jThOFP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jThOFPActionPerformed(evt);
            }
        });

        jThOHP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jThOHPActionPerformed(evt);
            }
        });

        jThOSS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jThOSSActionPerformed(evt);
            }
        });

        jThOJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jThOJActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25)
                    .addComponent(jLabel26)
                    .addComponent(jLabel27)
                    .addComponent(jLabel28))
                .addGap(80, 80, 80)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel32)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jThOJ))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel31)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jThOSS))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel30)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jThOHP))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel29)
                        .addGap(44, 44, 44)
                        .addComponent(jThOFP)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(jLabel29)
                    .addComponent(jThOFP))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(jLabel30)
                    .addComponent(jThOHP))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(jLabel31)
                    .addComponent(jThOSS))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(jLabel32)
                    .addComponent(jThOJ))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jBack4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 133, Short.MAX_VALUE)
                        .addComponent(ThOrderButton))
                    .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBack4)
                    .addComponent(ThOrderButton))
                .addContainerGap())
        );

        jTabbedPane2.addTab("Thursday", jPanel4);

        jBack5.setText("Back");
        jBack5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBack5ActionPerformed(evt);
            }
        });

        FOrderButton.setText("Order");
        FOrderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FOrderButtonActionPerformed(evt);
            }
        });

        jLabel33.setBackground(new java.awt.Color(255, 153, 0));
        jLabel33.setText("Full Panini");
        jLabel33.setOpaque(true);

        jLabel34.setBackground(new java.awt.Color(51, 255, 51));
        jLabel34.setText("Half Panini");
        jLabel34.setOpaque(true);

        jLabel35.setBackground(new java.awt.Color(255, 0, 0));
        jLabel35.setText("Sausage Roll");
        jLabel35.setOpaque(true);

        jLabel36.setBackground(new java.awt.Color(51, 255, 51));
        jLabel36.setText("Apple Juice");
        jLabel36.setOpaque(true);

        jLabel37.setText("£2.00");

        jLabel38.setText("£1.00");

        jLabel39.setText("£1.20");

        jLabel40.setText("£0.80");

        jFOFP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFOFPActionPerformed(evt);
            }
        });

        jFOHP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFOHPActionPerformed(evt);
            }
        });

        jFOSR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFOSRActionPerformed(evt);
            }
        });

        jFOJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFOJActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel33)
                    .addComponent(jLabel34)
                    .addComponent(jLabel35)
                    .addComponent(jLabel36))
                .addGap(86, 86, 86)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel39)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jFOSR))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel38)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jFOHP))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel37)
                        .addGap(44, 44, 44)
                        .addComponent(jFOFP))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel40)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jFOJ)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(jLabel37)
                    .addComponent(jFOFP))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(jLabel38)
                    .addComponent(jFOHP))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jFOSR, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel35)
                        .addComponent(jLabel39)))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(jLabel40)
                    .addComponent(jFOJ))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jBack5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(FOrderButton))
                    .addComponent(jPanel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBack5)
                    .addComponent(FOrderButton))
                .addContainerGap())
        );

        jTabbedPane2.addTab("Friday", jPanel5);

        jLabel41.setText("Balance:");

        try{
            jBalLabel.setText("£" + DBAccess.getBalance(SecScreen.user) );
        }catch(Exception e){

        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel41)
                    .addComponent(jBalLabel))
                .addGap(0, 15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel41)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBack5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBack5ActionPerformed
        //FRITAB returns to previous screen
        MainMenu Info = new MainMenu();
        Info.setVisible(true);
        dispose();
    }//GEN-LAST:event_jBack5ActionPerformed

    private void jBack4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBack4ActionPerformed
        //THURSTAB returns to main menu
        MainMenu Info = new MainMenu();
        Info.setVisible(true);
        dispose();
    }//GEN-LAST:event_jBack4ActionPerformed

    private void jBack3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBack3ActionPerformed
        //WEDTAB returns to main menu
        MainMenu Info = new MainMenu();
        Info.setVisible(true);
        dispose();
    }//GEN-LAST:event_jBack3ActionPerformed

    private void jBack2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBack2ActionPerformed
        //TUESTAB returns to main menu 
        MainMenu Info = new MainMenu();
        Info.setVisible(true);
        dispose();
    }//GEN-LAST:event_jBack2ActionPerformed

    private void jBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBack1ActionPerformed
        //MONTAB returns to main menu
        MainMenu Info = new MainMenu();
        Info.setVisible(true);
        dispose();
    }//GEN-LAST:event_jBack1ActionPerformed

    private void MOrderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MOrderButtonActionPerformed
        //MONTAB Order button pressed
        try {
            //Selects if user has enough money for selected order
            Color def = new Color(212, 208, 200, 255);
            float cost = mon.getCost();
            if (cost > DBAccess.getBalance(SecScreen.user)) {
                //NO ORDER error message shown
                MOrderButton.setBackground(Color.red);
                JOptionPane.showMessageDialog(null, "Error: Not enough money in account.", "Transaction error", JOptionPane.ERROR_MESSAGE);
                MOrderButton.setBackground(def);
            } else {
                //order carried out and database updated accordingly in 
                //appopriate tables
                MOrderButton.setBackground(def);
                mon.updateOrder();
                mon.confirm();
                
                //ensures database keeps money values in correct format and no 
                //rouning errors occur
                DecimalFormat df = new DecimalFormat("#.##");
                Double total = (double) (DBAccess.getBalance(SecScreen.user) - cost);
                total = Double.parseDouble(df.format(total));  

                DBAccess.setBalance(total, SecScreen.user);
                jBalLabel.setText("£" + DBAccess.getBalance(SecScreen.user));
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_MOrderButtonActionPerformed

    private void jTOHPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTOHPActionPerformed
        //updates array spaces for product in order object if checkbox selected
        if (jTOHP.isSelected()) {
            tues.HPOrder += 1;
            tues.ordbool[1] = true;
        } else {
            tues.HPOrder -= 1;
            tues.ordbool[1] = false;
        }
    }//GEN-LAST:event_jTOHPActionPerformed

    private void jThOFPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jThOFPActionPerformed
        //updates array spaces for product in order object if checkbox selected
        if (jThOFP.isSelected()) {
            thurs.FPOrder += 1;
            thurs.ordbool[0] = true;
        } else {
            thurs.FPOrder -= 1;
            thurs.ordbool[0] = false;
        }
    }//GEN-LAST:event_jThOFPActionPerformed

    private void jThOSSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jThOSSActionPerformed
        //updates array spaces for product in order object if checkbox selected
        if (jThOSS.isSelected()) {
            thurs.SSOrder += 1;
            thurs.ordbool[4] = true;
        } else {
            thurs.SSOrder -= 1;
            thurs.ordbool[4] = false;
        }
    }//GEN-LAST:event_jThOSSActionPerformed

    private void jThOJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jThOJActionPerformed
        //updates array spaces for product in order object if checkbox selected
        if (jThOJ.isSelected()) {
            thurs.JOrder += 1;
            thurs.ordbool[5] = true;
        } else {
            thurs.JOrder -= 1;
            thurs.ordbool[5] = false;
        }
    }//GEN-LAST:event_jThOJActionPerformed

    private void jFOSRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFOSRActionPerformed
        //updates array spaces for product in order object if checkbox selected
        if (jFOSR.isSelected()) {
            fri.SROrder += 1;
            fri.ordbool[3] = true;
        } else {
            fri.SROrder -= 1;
            fri.ordbool[3] = false;
        }
    }//GEN-LAST:event_jFOSRActionPerformed

    private void TOrderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TOrderButtonActionPerformed
        //TUESTAB Order button pressed
        try {
            //variables set and decides if user has enough money
            Color def = new Color(212, 208, 200, 255);
            float cost = tues.getCost();
            if (cost > DBAccess.getBalance(SecScreen.user)) {
                //NO ORDER, error message
                MOrderButton.setBackground(Color.red);
                JOptionPane.showMessageDialog(null, "Error: Not enough money in account.", "Transaction error", JOptionPane.ERROR_MESSAGE);
                MOrderButton.setBackground(def);
            } else {
                //order carried out, database is updated in all 3 tables 
                //to include order
                MOrderButton.setBackground(def);
                tues.updateOrder();
                tues.confirm();

                DecimalFormat df = new DecimalFormat("#.##");
                Double total = (double) (DBAccess.getBalance(SecScreen.user) - cost);
                total = Double.parseDouble(df.format(total));

                DBAccess.setBalance(total, SecScreen.user);
                jBalLabel.setText("£" + DBAccess.getBalance(SecScreen.user));
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_TOrderButtonActionPerformed

    private void jTOFPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTOFPActionPerformed
        //updates array spaces for product in order object if checkbox selected
        if (jTOFP.isSelected()) {
            tues.FPOrder += 1;
            tues.ordbool[0] = true;
        } else {
            tues.FPOrder -= 1;
            tues.ordbool[0] = false;
        }
    }//GEN-LAST:event_jTOFPActionPerformed

    private void jTOMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTOMActionPerformed
        //updates array spaces for product in order object if checkbox selected
        if (jTOM.isSelected()) {
            tues.MOrder += 1;
            tues.ordbool[2] = true;
        } else {
            tues.MOrder -= 1;
            tues.ordbool[2] = false;
        }
    }//GEN-LAST:event_jTOMActionPerformed

    private void jTOJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTOJActionPerformed
        //updates array spaces for product in order object if checkbox selected
        if (jTOJ.isSelected()) {
            tues.JOrder += 1;
            tues.ordbool[5] = true;
        } else {
            tues.JOrder -= 1;
            tues.ordbool[5] = false;
        }
    }//GEN-LAST:event_jTOJActionPerformed

    private void jWOFPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jWOFPActionPerformed
        //updates array spaces for product in order object if checkbox selected
        if (jWOFP.isSelected()) {
            wed.FPOrder += 1;
            wed.ordbool[0] = true;
        } else {
            wed.FPOrder -= 1;
            wed.ordbool[0] = false;
        }
    }//GEN-LAST:event_jWOFPActionPerformed

    private void jWOHPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jWOHPActionPerformed
        //updates array spaces for product in order object if checkbox selected
        if (jWOHP.isSelected()) {
            wed.HPOrder += 1;
            wed.ordbool[1] = true;
        } else {
            wed.HPOrder -= 1;
            wed.ordbool[1] = false;
        }
    }//GEN-LAST:event_jWOHPActionPerformed

    private void jWOSRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jWOSRActionPerformed
        //updates array spaces for product in order object if checkbox selected
        if (jWOSR.isSelected()) {
            wed.SROrder += 1;
            wed.ordbool[3] = true;
        } else {
            wed.SROrder -= 1;
            wed.ordbool[3] = false;
        }
    }//GEN-LAST:event_jWOSRActionPerformed

    private void jWOJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jWOJActionPerformed
        //updates array spaces for product in order object if checkbox selected
        if (jWOJ.isSelected()) {
            wed.JOrder += 1;
            wed.ordbool[5] = true;
        } else {
            wed.JOrder -= 1;
            wed.ordbool[5] = false;
        }
    }//GEN-LAST:event_jWOJActionPerformed

    private void WOrderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WOrderButtonActionPerformed
        //WEDSTAB order button pressed
        try {
            //decides if user can proceed with order or not
            Color def = new Color(212, 208, 200, 255);
            float cost = wed.getCost();
            if (cost > DBAccess.getBalance(SecScreen.user)) {
                //NO ORDER error message shown
                MOrderButton.setBackground(Color.red);
                JOptionPane.showMessageDialog(null, "Error: Not enough money in account.", "Transaction error", JOptionPane.ERROR_MESSAGE);
                MOrderButton.setBackground(def);
            } else {
                //Order carried out, order object updated and sent to DB
                MOrderButton.setBackground(def);
                wed.updateOrder();
                wed.confirm();

                //ensures DB keeps correct format and no rounding errors occur
                DecimalFormat df = new DecimalFormat("#.##");
                Double total = (double) (DBAccess.getBalance(SecScreen.user) - cost);
                total = Double.parseDouble(df.format(total));

                DBAccess.setBalance(total, SecScreen.user);
                jBalLabel.setText("£" + DBAccess.getBalance(SecScreen.user));
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_WOrderButtonActionPerformed

    private void jThOHPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jThOHPActionPerformed
        //updates array spaces for product in order object if checkbox selected
        if (jThOHP.isSelected()) {
            thurs.HPOrder += 1;
            thurs.ordbool[1] = true;
        } else {
            thurs.HPOrder -= 1;
            thurs.ordbool[1] = false;
        }
    }//GEN-LAST:event_jThOHPActionPerformed

    private void ThOrderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThOrderButtonActionPerformed
        //THURSORDER Order button pressed
        try {
            //decides if user can carry out order or not
            Color def = new Color(212, 208, 200, 255);
            float cost = thurs.getCost();
            if (cost > DBAccess.getBalance(SecScreen.user)) {
                //NO ORDER, error message shown
                MOrderButton.setBackground(Color.red);
                JOptionPane.showMessageDialog(null, "Error: Not enough money in account.", "Transaction error", JOptionPane.ERROR_MESSAGE);
                MOrderButton.setBackground(def);
            } else {
                //Order carried out, database updated as neeeded
                MOrderButton.setBackground(def);
                thurs.updateOrder();
                thurs.confirm();

                //ensures no rounding errors and database keeps money in correct
                //format
                DecimalFormat df = new DecimalFormat("#.##");
                Double total = (double) (DBAccess.getBalance(SecScreen.user) - cost);
                total = Double.parseDouble(df.format(total));

                DBAccess.setBalance(total, SecScreen.user);
                jBalLabel.setText("£" + DBAccess.getBalance(SecScreen.user));
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_ThOrderButtonActionPerformed

    private void jFOFPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFOFPActionPerformed
        //updates array spaces for product in order object if checkbox selected
        if (jFOFP.isSelected()) {
            fri.FPOrder += 1;
            fri.ordbool[0] = true;
        } else {
            fri.FPOrder -= 1;
            fri.ordbool[0] = false;
        }
    }//GEN-LAST:event_jFOFPActionPerformed

    private void jFOHPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFOHPActionPerformed
        //updates array spaces for product in order object if checkbox selected
        if (jFOHP.isSelected()) {
            fri.HPOrder += 1;
            fri.ordbool[1] = true;
        } else {
            fri.HPOrder -= 1;
            fri.ordbool[1] = false;
        }
    }//GEN-LAST:event_jFOHPActionPerformed

    private void FOrderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FOrderButtonActionPerformed
        //FRITAB Order button pressed
        try {
            //decides if user has enough money to continue order
            Color def = new Color(212, 208, 200, 255);
            float cost = fri.getCost();
            if (cost > DBAccess.getBalance(SecScreen.user)) {
                //NO ORDER, error shown to user
                MOrderButton.setBackground(Color.red);
                JOptionPane.showMessageDialog(null, "Error: Not enough money in account.", "Transaction error", JOptionPane.ERROR_MESSAGE);
                MOrderButton.setBackground(def);
            } else {
                //Order carried out, database updated to hold order
                MOrderButton.setBackground(def);
                fri.updateOrder();
                fri.confirm();

                //formatting for money values in database
                DecimalFormat df = new DecimalFormat("#.##");
                Double total = (double) (DBAccess.getBalance(SecScreen.user) - cost);
                total = Double.parseDouble(df.format(total));

                DBAccess.setBalance(total, SecScreen.user);
                jBalLabel.setText("£" + DBAccess.getBalance(SecScreen.user));
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_FOrderButtonActionPerformed

    private void jMOJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMOJActionPerformed
        //updates array spaces for product in order object if checkbox selected
        if (jMOJ.isSelected()) {
            mon.JOrder += 1;
            mon.ordbool[5] = true;
        } else {
            mon.JOrder -= 1;
            mon.ordbool[5] = false;
        }
    }//GEN-LAST:event_jMOJActionPerformed

    private void jMOSSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMOSSActionPerformed
        //updates array spaces for product in order object if checkbox selected
        if (jMOSS.isSelected()) {
            mon.SSOrder += 1;
            mon.ordbool[4] = true;
        } else {
            mon.SSOrder -= 1;
            mon.ordbool[4] = false;
        }
    }//GEN-LAST:event_jMOSSActionPerformed

    private void jMOHPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMOHPActionPerformed
        //updates array spaces for product in order object if checkbox selected
        if (jMOHP.isSelected()) {
            mon.HPOrder += 1;
            mon.ordbool[1] = true;
        } else {
            mon.HPOrder -= 1;
            mon.ordbool[1] = false;
        }
    }//GEN-LAST:event_jMOHPActionPerformed

    private void jMOFPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMOFPActionPerformed
        //updates array spaces for product in order object if checkbox selected
        if (jMOFP.isSelected()) {
            mon.FPOrder += 1;
            mon.ordbool[0] = true;
        } else {
            mon.FPOrder -= 1;
            mon.ordbool[0] = false;
        }
    }//GEN-LAST:event_jMOFPActionPerformed

    private void jFOJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFOJActionPerformed
        // TODO add your handling code here:
        //updates array spaces for product in order object if checkbox selected
        if (jFOJ.isSelected()) {
            fri.JOrder += 1;
            fri.ordbool[5] = true;
        } else {
            fri.JOrder -= 1;
            fri.ordbool[5] = false;
        }
    }//GEN-LAST:event_jFOJActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jOrderMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jOrderMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jOrderMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jOrderMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jOrderMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton FOrderButton;
    private javax.swing.JButton MOrderButton;
    private javax.swing.JButton TOrderButton;
    private javax.swing.JButton ThOrderButton;
    private javax.swing.JButton WOrderButton;
    private javax.swing.JButton jBack1;
    private javax.swing.JButton jBack2;
    private javax.swing.JButton jBack3;
    private javax.swing.JButton jBack4;
    private javax.swing.JButton jBack5;
    private javax.swing.JLabel jBalLabel;
    private javax.swing.JCheckBox jFOFP;
    private javax.swing.JCheckBox jFOHP;
    private javax.swing.JCheckBox jFOJ;
    private javax.swing.JCheckBox jFOSR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JCheckBox jMOFP;
    private javax.swing.JCheckBox jMOHP;
    private javax.swing.JCheckBox jMOJ;
    private javax.swing.JCheckBox jMOSS;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JCheckBox jTOFP;
    private javax.swing.JCheckBox jTOHP;
    private javax.swing.JCheckBox jTOJ;
    private javax.swing.JCheckBox jTOM;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JCheckBox jThOFP;
    private javax.swing.JCheckBox jThOHP;
    private javax.swing.JCheckBox jThOJ;
    private javax.swing.JCheckBox jThOSS;
    private javax.swing.JCheckBox jWOFP;
    private javax.swing.JCheckBox jWOHP;
    private javax.swing.JCheckBox jWOJ;
    private javax.swing.JCheckBox jWOSR;
    // End of variables declaration//GEN-END:variables
}
